version: "3"

services:
  auth-golang:
    container_name: auth-golang
    build:
      context: ./golang
    ports:
      - 3000:3000
    environment:
      - FEED_API_KEY=ABCD
      - REPOSITORY_CONNECTION_STRING=memory://
    depends_on: 
      - redis
    

  auth-python:
    container_name: auth-python
    build: 
      context: ./python
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis
    command: redis-server --requirepass REDIS
    hostname: redis
    ports:
      - "6379:6379"
